### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by Adurol** [KaOS-Community-Packages/texstudio#1]
Can't get it to build, I'll get the error

```
Makefile:6892: recipe for target '.obj/PDFDocument.o' failed
make: *** [.obj/PDFDocument.o] Error 1
==> ERROR: A failure occurred in build().
```

**Comment by forostm** [comment]
Correction in [0aa0e8c](https://github.com/KaOS-Community-Packages/texstudio/commit/0aa0e8c416405024f4099acd13ba586c2854bc8c)
